### ISSUE TITLE
raft.addPeer($enodeInfo) no respond

### ISSUE THREAD

**Issue by Max-Pano** [Szkered/quorum-raft-cluster#1]
After "geth attach" a node,
The first time "raft.addPeer", the console get returned
But the second time "raft.addPeer" is execute, nothing console returned.
And I have to "ctrl + z" and reattach

**Comment by zekun-shi** [comment]
Hi, can you elaborate what you did? Did you add the same peer twice?

**Comment by Max-Pano** [comment]
Hi, I added two different peers, one after another, like this:
`raft.addPeer("enode://2252a5ad172f74bcf5b74c646a03946062d005dca96be8100ce507ecc20c3b05c5e301a865be7bd6ed771d39d6759406846a648db9042f3df8cb6e40c9e91e27@172.16.125.49:21000?discport=0&raftport=23000")`
`raft.addPeer("enode://307be0fb6f6523baf2127fcc560321861d23a598516a4dfd2a51ce3e3cba80517d278710724f1615f5e45a6d25e4c29ccde3954fd84ce8dcb3e303096922e062@172.16.125.53:21000?discport=0&raftport=23000")`

By the way, does the `raftId` need to be the same with nodes?
I've tried "$raftId" configured with different nodes and the result is same as before.

And I also set the "othernodes" like below, I have 3 nodes:
`othernodes = ["http://172.16.125.49:9001/","http://172.16.125.51:9001/"]`

**Comment by Max-Pano** [comment]
And the other problem is, even I use `addPeer` for once between 2 nodes, and `admin.peers` shows they both connected to each other, there is no block was made, `eth.blockNumber` is 0.

And after transaction test only txpool shows the tx, but no block.
I wonder what I did wrong or something, please help.

**Comment by zekun-shi** [comment]
One key thing that is undocumented is the peer list (`static-nodes.json`) The peer list need to be in the SAME ORDER for all the nodes, as array index is the raftId. Once the initial cluster is launched the `static-nodes.json` is loaded into DB, and when you do `raft.addPeer(...)` you are essentially appending enodeInfo to that list inside the DB.

For dynamic raft, there's basically two stage:
1. Bringing up the initial cluster with exactly the same `static-nodes.json`
2. Bring up the new node: Copy the `static-nodes.json` from the existing cluster to your new node, and append the enodeInfo of itself to that. After you bring the new node up, you can do `raft.addPeer(...)` from any node in the existing cluster.

**Comment by Max-Pano** [comment]
Hi, Szkered. I've tried the specific steps you mentioned and It does work,
I thought the new node to be add don't need the `static-nodes.json` changed.
So that what I did wrong.
And I know that the raft only produce new block when there are transactions.
Thanks. So I can do some speed test now😄
