### ISSUE TITLE
Issue in Setting up Quorum Client-Not able to attach to geth client

### ISSUE THREAD

**Issue by mariam-crissi** [Szkered/quorum-raft-cluster#3]
I am trying to setup Quorum private net.The following are the steps I have followed.

              sudo ./get-quorum.sh

The ```./get-quorum.sh``` command successfully installed Quorum and created a folder ```quorum``` in the directory. 

            sudo ./raft-setup.sh

It produces the following output.

            [*] Cleaning up temporary data directories
            [*] Generating geth node config
            [*] Stopping geth
            [*] Generating constellation key pair
           Lock key pair constellation with password [none]: 
           ./raft-setup.sh: line 22:  8775 Terminated              nohup geth --datadir raft 2>> raft/setup.log  (wd: ~/Documents/quorum-raft-cluster-master)
          [*] Done

It generates the folder ```raft```.And created a raft/static-nodes.json with the generated enode info as follows.

         ["enode://b0bc4d823c9560cc87051e5dec986f28538e8b87a62f5786e36b9e15f7f299f754d827bc29496c254425d0522d1556825fff0df8e35ba63b9d4f88f3f7b96f3d@
```enode://b0bc4d823c9560cc87051e5dec986f28538e8b87a62f5786e36b9e15f7f299f754d827bc29496c254425d0522d1556825fff0df8e35ba63b9d4f88f3f7b96f3d@127.0.0.1:21000?discport=0&raftport=23000"]```

The genesis file in the folder is predefined with two accounts.So I have left it as it is for my node.

Then produced the command  ```sudo ./raft-init.sh```. It initializes the quorum instance as follows.

              [*] Cleaning up temporary data directories
              [*] Configuring node
              INFO [12-01|10:15:05] Allocated cache and file handles         database=/home/maria/Documents/quorum-raft-cluster-master/qdata/geth/chaindata cache=16 handles=16
              INFO [12-01|10:15:05] Writing custom genesis block 
              INFO [12-01|10:15:05] Successfully wrote genesis state         database=chaindata                                                             hash=200e14…628c52
              INFO [12-01|10:15:05] Allocated cache and file handles         database=/home/maria/Documents/quorum-raft-cluster-master/qdata/geth/lightchaindata cache=16 handles=16
              INFO [12-01|10:15:05] Writing custom genesis block 
              INFO [12-01|10:15:05] Successfully wrote genesis state         database=lightchaindata                                                             hash=200e14…628c52
 The above command generates the ```qdata``` folder in the directory.             
 Then I have produced the next command as mentioned ```sudo ./constellation-start.sh```.
It returns the following output.
 
                         [*] Starting Constellation node
 It generates the ```tm.ipc``` file in the folder ```qdata```.I hope,it is the file which deals with the ipc connection of constellation node.
     
Then I am starting geth node as follows ``` sudo ./raft-start.sh```. It returns the following output.
                   
                        [*] Starting geth node
    
I haven't found any ```geth.ipc``` in ```qdata``` folder.Instead I have found a ```geth.ipc``` file in raft folder.

Then as mentioned,I tried to attach to the geth console as follows.

                      sudo geth attach qdata/geth.ipc
                      Fatal: Unable to attach to remote geth: dial unix qdata/geth.ipc: connect: no such file or directory
Then I tried to attach to constellation node as follows.

                    sudo geth attach qdata/tm.ipc
                    Fatal: Failed to start the JavaScript console: api modules: context deadline exceeded

Please help me to resolve these issues.

**Comment by mariam-crissi** [comment]
This issue was due the faulty generation of enode info in static-nodes.json file..I have corrected the file and solved the issue.

**Comment by sambhavgaur** [comment]
similar issue, any help is appreciated. How to fix it?

../quorum-examples/examples/5nodesRTGS$ geth attach ipc:qdata/tm1.ipc
Fatal: Failed to start the JavaScript console: api modules: context deadline exceeded

**Comment by porteron** [comment]
This issue is still persisting. `geth.ipc` is not being generated in the `qdata` folder

**Comment by ghost** [comment]
I have the same issue. The ipc files are not being generated by the shell scripts.
