### ISSUE TITLE
non-interactive mode for "raft-setup.sh"

### ISSUE THREAD

**Issue by oleksiikoshlatyi** [Szkered/quorum-raft-cluster#7]
It will have interactive mode:
constellation-node --generatekeys=constellation

But you can change it to:
#Lock constellation key pair with password:
CONSTELLATION-KEY-PASSWORD=""
echo $CONSTELLATION-KEY-PASSWORD | constellation-node --generatekeys=constellation

It will help to use the script in automatical (non-interactive) mode

**Comment by zekun-shi** [comment]
PR merged
